name: whisqr2
description: A sample command-line application.
version: 1.0.0
homepage: https://www.sketchdm.co.za

environment:
  sdk: '>=2.7.0 <3.0.0'

dependencies:
 path: ^1.6.0
 dio: ^3.0.7
 crypto: ^2.1.4
 json_annotation: ^2.0.0

dev_dependencies:
  pedantic: ^1.8.0
  test: ^1.6.0
  build_runner: ^1.0.0
  json_serializable: ^2.0.0
